version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: problem_2_python/Dockerfile
    container_name: acme_log_backend
    ports:
      - "8000:8000"
    restart: always

  rag-app:
    build:
      context: .
      dockerfile: problem_3_rag/Dockerfile
    container_name: acme_rag_app
    ports:
      - "8001:8001"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY} # Passes host GEMINI_API_KEY to container if set
    depends_on:
      - backend
    restart: always
